openapi: 3.0.0
info:
   title: Adding to cart
   version: 1.0.0
   description: Описание методов взимодействия пользователя с корзиной товаров со страницы товара
paths:
  /items/{item_id}:
     get:
       summary: Получить данные о товаре
       parameters: 
          - name: item_id
            in: path
            required: true
            description: Идентификатор товара
            schema:
              type: integer
              example: 1567
       responses:
         '200':
           description: Информация о товаре
           content:
             application/json:
               schema:
                 type: object
                 properties:
                   id: 
                     type: integer
                     example: 1567
                   name:
                     type: string
                     example: 'Spotify'
                   price:
                     type: number
                     example: '1799'
                   filters:
                     type: object
                     example: 
                       Period: '3 Month'
                       Additional: 'Create account'
         '410':
           description: Товар недоступен
         '409':
           description: Товар закончился