openapi: 3.0.0
info:
   title: Adding to cart
   version: 1.0.0
   description: Описание методов взимодействия пользователя с корзиной товаров со страницы товара
paths:
  /cart/items/{item_id}:
     post:
       summary: Добавить товар в корзину
       description: Добавляет товар в корзину с количеством 1
       parameters:
         - name: item_id
           in: path
           required: true
           description: Идентификатор товара
           schema:
             type: integer
             example: 1567
       requestBody:
         required: true
         description: выбранные пользователем опции товара
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/addToCartRequest'
       responses:
          '201':
           description: Товар добавлен в корзину
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/addToCartResponse'
          '404':
             description: Товар недоступен
          '409':
             description: Невозможно добавить в корзину (Товар закончился)
             
components:
   schemas:
     addToCartRequest:
       type: object
       properties:
         filters: 
           type: object
           description: Выбранные пользователем опции
           example: 
             Period: '3 Month'
             Addiction: 'Creating account'
         quantity:
           type: integer
           description: Количество товара в корзине после добавления
           example: 1
     addToCartResponse:
       type: object
       properties:
         item_id: 
           type: integer
           example: 1567
         name:
           type: string
           example: 'Spotify'
         quantity:
           type: integer
           description: Количество товара в корзине после добавления
           example: 1
         status:
           type: string
           example: 'added'
         
           
           
           
